### ISSUE TITLE
Android App Issues: Pack Creation/Profile/Feed

### ISSUE THREAD

**Issue by EngrAJ8888** [andrew-bierman/PackRat#1014]
**Describe the bug**

Unable to add more items to the pack: The "Add item" button overlaps with the menu at the bottom of the screen, and I cannot scroll down the page.
![image](https://github.com/andrew-bierman/PackRat/assets/122357250/d27a7a05-40df-4b6d-a892-976e9956d36f)

The cloned pack feature isn't working properly. It causes the app to crash.
![image](https://github.com/andrew-bierman/PackRat/assets/122357250/fadfa0f1-bbaa-4517-b8f4-ae4b25a63765)

Add back/reroute option in the profile settings: Users should be redirected to the user profile page when clicking on this option.
![image](https://github.com/andrew-bierman/PackRat/assets/122357250/e985a55b-10b1-4cb0-9cdf-d54c599e0961)

**Comment by Isthisanmol** [comment]
Hi @EngrAJ8888, first one is fixed in PR: #1010. Please check.

**Comment by EngrAJ8888** [comment]
Hi @Isthisanmol - this is noted.

I've added some items that needs fixes, please refer below:

- [ ] Update the text on Pack/Feed/Trips. The user link and Favorites are almost overlapping.
![image](https://github.com/andrew-bierman/PackRat/assets/122357250/6bcf5507-19c9-46df-9daa-a099c0be5900)

- [ ] Update the display of Packs weight across all pages (like in user profile) to show only up to 2 decimal points. Additionally, adjust the container to prevent it from being cut off.
![image](https://github.com/andrew-bierman/PackRat/assets/122357250/578305af-8b9a-4f43-b8b9-7b143a87d57e)

- [ ] When viewing the "See All" option in the User Profile Summary for Packs/Trips/Favorites, only 1 item is displayed, and the search bar is not functioning correctly, which leads to app crashes when used.
![image](https://github.com/andrew-bierman/PackRat/assets/122357250/52b27c21-5137-40cf-8ee4-f4c1a1546e76)

**Comment by pinocchio-life-like** [comment]
Hi, @Isthisanmol please see the comment I left on PR: https://github.com/andrew-bierman/PackRat/pull/1019 ( its been merged but its breaking some pages on web, I am not sure if it was intentional )

**Comment by Isthisanmol** [comment]
Hi, @EngrAJ8888 please check  #1025. I think it closes this issue.

**Comment by EngrAJ8888** [comment]
Hi @Isthisanmol - thanks for the update! There's still an issue when scrolling on the "Create a Pack" screen. Please check the video below for reference.

https://github.com/andrew-bierman/PackRat/assets/122357250/302a516e-7c72-44d9-9a7e-1a5c20f98d98
